- Clean_home:
    - exec_in: rm -rf ~$$user_name/*
- Create_tmp_directories:
    - exec_in_user:
        - $$user_name
        - mkdir -p /home/$$user_name/Documents_tmp && mkdir -p /home/$$user_name/Documents_tmp

# Copy the ssh_key for virtual images
- ssh_key:
    - exec_in_user:
        - $$user_name
        - mkdir -p /home/$$user_name/.ssh
    - local2in:
        - $$kameleon_cwd/../../files/id_rsa_virt
        - /home/$$user_name/.ssh/id_rsa_virt
    - local2in:
        - $$kameleon_cwd/../../files/id_rsa_virt.pub
        - /home/$$user_name/.ssh/id_rsa_virt.pub
    - local2in:
        - $$kameleon_cwd/../../files/ssh_config
        - /home/$$user_name/.ssh/config
    - exec_in: chown -R $$user_name:$$user_name /home/$$user_name/.ssh/
    - exec_in_user:
        - $$user_name
        - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*

# Retrieve configuration files and script
- copy_configuration:
    - local2in_dir:
        - /home/$$user_name/Documents/Conf
        - /home/$$user_name/conf
- install_configuration:
    - exec_in_user:
        - $$user_name
        - rm ~/.vim*; cd ~/conf; ./install.sh -f -t;
- copy_scripts:
    - local2in_dir:
        - /home/$$user_name/scripts
        - /home/$$user_name/scripts

#Copy files from host
- copy_work_files:
    - local2in_dir:
        - /home/$$user_name/Work/Moca
        - /home/$$user_name/Work/Moca
    - local2in_dir:
        - /home/$$user_name/Work/Bench/matrix
        - /home/$$user_name/Work/Bench/matrix
    - exec_in: chown -R $$user_name:$$user_name /home/$$user_name/Work/

- fix_permissions:
    -exec_in: chmod -R $$user_name:$$user_name /home/$$user_name

# Easy unsecure root access
- exec_in : echo -e "$$user_password\n$$user_password\n" | passwd
